### ISSUE TITLE
Kill switch?

### ISSUE THREAD

**Issue by cm157** [dragonfruitnetwork/onionfruit#13]
I guess most important feature from anonymity POV does it have any mechanism to prevent leak of real IP? Iptables, etc. if the tor network inadvertently disconnects without the user noticing or while network activity is ongoing

**Comment by aspriddell** [comment]
there are a couple of potential situations:
- if the tor network disconnects from the tor client, pages will fail to load with a proxy error (if they use the system proxy)
- if the tor process itself is killed (i.e. task manager) onionfruit will detect that and perform a graceful disconnect.

as for the latter, it's highly unlikely and the main reason onionfruit does this is to stop people people from freaking out when chrome/any other app cannot connect because the proxy settings weren't cleaned up. there could be an option flag where if the process is killed it can send a notification and refuse to cleanup (simulating option 1) if that'd make the program feel safer?

**Comment by cm157** [comment]
It's up to you. If you don't implement a hard coded kill switch and robust safeguards to prevent leaks you need to provide potential users with adequate warning about (imho significant) risks. A lot of scenarios that might result in some type of failure and network activity to egress over a insecure network. With anonymity it only takes one packet of data to escape the tunnel to undo all efforts to obfuscate. I personally see little value providing users with the tools to be anonymous and not the needed protection to safeguard it.

**Comment by cm157** [comment]
I accidentally deleted my post 

![image](https://user-images.githubusercontent.com/71204465/111916669-42000a80-8a39-11eb-9490-b77cb76b7fa0.jpeg)

**Comment by aspriddell** [comment]
i don't see the harm in adding a notification

**Comment by aspriddell** [comment]
sorry for delayed response, was waiting for [another component](https://github.com/dragonfruitnetwork/onionfruit-geoip) to fully test before updating. It's now live in [2020.322](https://dragonfruit.network/changelog/onionfruit/2021.322) (as a beta release for now)

feel free to open another issue if there's another problem/suggestion
