### ISSUE TITLE
Discord No Route issue

### ISSUE THREAD

**Issue by QuMix64** [dragonfruitnetwork/onionfruit#51]
![image](https://github.com/user-attachments/assets/c052f584-d8ae-4ab3-a8f4-7a10c59cdfdb)

Hello, OnionFruit works perfect after fixing bug with connection to tor through bridges, thank you! However, I noticed one problem related to Discord. I wonder if it is possible to fix "No route" issue?

**Comment by aspriddell** [comment]
I tried on both desktop and web and had no issue joining a channel, whether that's due to it bypassing the proxy on your end and failing as a result or not I couldn't tell you.

We can't support individual apps unless there's a specific setting that needs to be toggled in the torrc file needs enabled/set. If you are opening your browser and the tor/dragonfruit website says you're then that means the app is functioning as expected.

---

I've had the same experience trying to use these kind of VoIP apps on networks that require proxies and it's usually due to them not knowing how to proxy these requests (they don't respect the settings given to them). I'm fairly sure Discord uses WebRTC under the hood and I wouldn't be suprised if it doesn't handle proxies well. To get around that you'd need to use a VPN.

I would also check the web version and see if you get a better result but that's about all the support that can be provided.
