### ISSUE TITLE
onionfruit Firewall

### ISSUE THREAD

**Issue by Zig-VS-TypeScript-VS** [dragonfruitnetwork/onionfruit#59]
onionfruit Firewall Or TUN Tunnel and virtual network adapter.

Onionfruit takes over the win10 firewall like antivirus apps.
Blocks all connections of non-allowed exe processes by default

**Comment by aspriddell** [comment]
This has been discussed before, and the reason this is unlikely to happen is because it breaks the key points of the project: OnionFruit doesn't require admin to install and leaves no permanent changes to your system.

Creating a TUN adapter would require drivers to be installed on user machines which doesn't work with the current system, and while things like [Windows Filtering Platform](https://learn.microsoft.com/en-us/windows/win32/fwp/windows-filtering-platform-start-page) could be used it's not going to work when other platforms are introduced later on.

For these reasons, there will be minimal effort directed towards this. You should consider tweaking windows firewall rules if you want this kind of control over network traffic on your computer.
